Revert GPU changes

diff --git a/diskimage_builder/elements/ubuntugpu/install.d/51-gpu b/diskimage_builder/elements/ubuntugpu/install.d/51-gpu
--- a/diskimage_builder/elements/ubuntugpu/install.d/51-gpu
+++ b/diskimage_builder/elements/ubuntugpu/install.d/51-gpu
@@ -1,45 +1,88 @@
 #!/bin/bash
 
-if [ "${DIB_RELEASE}" == "bionic" ]; then
-    distribution="ubuntu18.04"
+# Installation of general packages...
+apt-get -y install linux-headers-generic
+apt-get -y install python3-pip git software-properties-common python3-virtualenv
+python3 -m pip install --upgrade pip
+
+pip install setuptools
+add-apt-repository -y ppa:graphics-drivers/ppa
+
+# This installation follows the official installation guide: https://www.tensorflow.org/install/gpu
+# Check which Version needs to be installed here.
+if [ "${DIB_RELEASE}" == "xenial" ]; then
+    # Nvidia repo
+    NVIDIA_CUDA_REPO="http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/"
+    NVIDIA_CUDA_DEB="cuda-repo-ubuntu1604_8.0.61-1_amd64.deb"
+    NVIDIA_CUDA_KEY="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub"
+    NVIDIA_DRIVER_PKG="nvidia-driver-418"
+
+    NVIDIA_ML_REPO="http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/"
+    NVIDIA_ML_DEB="nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb"
+
+    # Add https support for apt-key (only necessary on Xenial)
+    apt-get install -y gnupg-curl
+
+elif [ "${DIB_RELEASE}" == "bionic" ]; then
+    # Nvidia repo
+    NVIDIA_CUDA_REPO="http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/"
+    NVIDIA_CUDA_DEB="cuda-repo-ubuntu1804_10.1.243-1_amd64.deb"
+    NVIDIA_CUDA_KEY="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub"
+    NVIDIA_DRIVER_PKG="nvidia-driver-418"
+    
+    # Get the machine-learning packages for the nvidia gpu
+    NVIDIA_ML_REPO="http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/"
+    NVIDIA_ML_DEB="nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb"
+
 elif [ "${DIB_RELEASE}" == "focal" ]; then
-    distribution="ubuntu20.04"
+    # Nvidia repo
+    NVIDIA_CUDA_REPO="http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/"
+    NVIDIA_CUDA_DEB="cuda-repo-ubuntu1804_10.2.89-1_amd64.deb"
+    NVIDIA_CUDA_KEY="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub"
+    NVIDIA_DRIVER_PKG="nvidia-driver-440"
+    
+    # Get the machine-learning packages for the nvidia gpu
+    NVIDIA_ML_REPO="http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/"
+    NVIDIA_ML_DEB="nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb"
+
 else
-    distribution="ubuntu18.04"
+    echo "Specified distribution release is not supported. DIB_RELEASE: ${DIB_RELEASE}"
+    exit 1
 fi
 
-# Add required packages and CUDA repository
-apt-get install -y linux-headers-$(uname -r)
-compact_distribution=$(echo $distribution | sed -e 's/\.//g')
-wget https://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64/cuda-$compact_distribution.pin
-mv cuda-$compact_distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600
-apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64/7fa2af80.pub
-echo "deb http://developer.download.nvidia.com/compute/cuda/repos/$compact_distribution/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
-
-# Install CUDA Drivers (includes nvidia-driver-X)
-apt-get update
-apt-get -y install cuda-drivers
-
-sed -i -e 's#PATH="#PATH="/usr/local/cuda-11.2/bin:#g' /etc/environment
-
-cp /lib/udev/rules.d/40-vm-hotadd.rules /etc/udev/rules.d
-sed -i -e 's/SUBSYSTEM=="memory", ACTION=="add"/#SUBSYSTEM=="memory", ACTION=="add"/g' /etc/udev/rules.d/40-vm-hotadd.rules
-
-# Add nvidia-docker/nvidia-toolkit if needed
-if [ "${UBUNTU_GPU_NVIDIA_TOOLKIT}" == "true" ]; then
-    # Use of Docker Image is recommended: https://www.tensorflow.org/install/gpu
-    # Many interdependencies can be packed into the image what's difficult for VM only installation.
-    # Furthermore, it decreases the Ubuntu GPU Image size massively.
-    curl https://get.docker.com | sh \
-        && systemctl enable docker
-
-    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
-        && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
-
-    apt-get update
-    apt-get install -y nvidia-docker2
-
-    # Test GPU Acess via:
-    # docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print('Num GPUs Available: ', len(tf.config.list_physical_devices('GPU')))"
-    # docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
+if [ ! -z "$NVIDIA_CUDA_DEB" ]; then
+    wget -nv $NVIDIA_CUDA_REPO$NVIDIA_CUDA_DEB
+    dpkg -i $NVIDIA_CUDA_DEB
+    rm ./$NVIDIA_CUDA_DEB
+    apt-key adv --fetch-keys $NVIDIA_CUDA_KEY
+    apt-get -y update
+else
+    echo "Failed to install CUDA. Missing NVIDIA_CUDA_DEB..."
+    exit 1
 fi
+
+
+# Install development and runtime
+# Install CUDA and cudnn, cuda
+wget -nv $NVIDIA_ML_REPO$NVIDIA_ML_DEB
+dpkg -i ./$NVIDIA_ML_DEB
+rm ./$NVIDIA_ML_DEB
+apt-get -y update
+# Install NVIDIA driver
+if [ ! -z "$NVIDIA_DRIVER_PKG" ]; then
+    # Install nvidia driver if necessary
+    apt-get install -y --no-install-recommends $NVIDIA_DRIVER_PKG
+fi
+
+apt-get install -y --no-install-recommends \
+cuda-10-0 \
+libcudnn7=7.6.2.24-1+cuda10.0  \
+libcudnn7-dev=7.6.2.24-1+cuda10.0
+
+# Install TensorRT. Requires that libcudnn7 is installed above.
+apt-get install -y --no-install-recommends libnvinfer5=5.1.5-1+cuda10.0 \
+libnvinfer-dev=5.1.5-1+cuda10.0
+
+# Install tensorflow-gpu 
+# --> There is a need to convert v1.X code to v2.X. See: https://www.tensorflow.org/guide/migrate
+pip install --upgrade tensorflow
